"""Per-tenant history schema for the hosted (Postgres) storage backend.

The desktop history database is built by ``ExecutionHistoryRepository.migrate``
(``SCHEMA_VERSION`` 10, migrations 1-10) through ``ALTER TABLE`` steps. A new
hosted tenant has no history to migrate, so it is created directly in the
final shape those migrations produce, and ``schema_migrations`` records every
version up to ``SCHEMA_VERSION`` so the two stores answer "which migrations
ran" identically. ``test_storage_remote.SchemaParityTests`` compares the tables,
columns and indexes with a freshly migrated SQLite database; bumping
``SCHEMA_VERSION`` therefore fails that test until this module follows.

The statements use only syntax Postgres and SQLite share (the tests run the
same text on both). Two deliberate differences from the SQLite file:
token counters and ``duration_ms`` are ``BIGINT`` (Postgres ``INTEGER`` is 32
bit), and ``ai_token_usage`` carries an identity column, ``seq``, because
Postgres has no ``rowid`` to keep a batch's insertion order.
"""

from __future__ import annotations

# ``{usage_seq}`` is the dialect's insertion-order column ("" on SQLite, where
# ``rowid`` already provides it).
HISTORY_STATEMENTS = (
    """CREATE TABLE IF NOT EXISTS ai_executions (
    execution_id TEXT PRIMARY KEY,
    repository TEXT NOT NULL,
    issue_number INTEGER NOT NULL,
    issue_url TEXT NOT NULL DEFAULT '',
    issue_title TEXT NOT NULL,
    original_issue_body TEXT NOT NULL,
    effective_prompt TEXT NOT NULL DEFAULT '',
    ai_provider TEXT NOT NULL,
    model TEXT NOT NULL DEFAULT '',
    effort TEXT NOT NULL DEFAULT '',
    reasoning_config TEXT NOT NULL DEFAULT '{}',
    started_at TEXT NOT NULL,
    completed_at TEXT,
    duration_seconds DOUBLE PRECISION,
    requested_work_summary TEXT NOT NULL DEFAULT '',
    changes_summary TEXT NOT NULL DEFAULT '',
    files_changed TEXT NOT NULL DEFAULT '[]',
    branch_name TEXT NOT NULL DEFAULT '',
    commit_shas TEXT NOT NULL DEFAULT '[]',
    pull_request_number INTEGER,
    pull_request_url TEXT NOT NULL DEFAULT '',
    operational_notes TEXT NOT NULL DEFAULT '[]',
    warnings_errors TEXT NOT NULL DEFAULT '[]',
    final_status TEXT NOT NULL,
    attempt_number INTEGER NOT NULL,
    application_version TEXT NOT NULL DEFAULT '',
    prompt_template_version TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL,
    uploaded_at TEXT,
    upload_status TEXT NOT NULL DEFAULT 'never_uploaded',
    upload_error TEXT NOT NULL DEFAULT '',
    uploaded_record_updated_at TEXT,
    reviewer_feedback TEXT NOT NULL DEFAULT '',
    reviewer_feedback_at TEXT,
    routing_decision TEXT NOT NULL DEFAULT '',
    adversarial_round_count INTEGER NOT NULL DEFAULT 0,
    adversarial_outcome TEXT NOT NULL DEFAULT '',
    capacity_consumed_percent DOUBLE PRECISION,
    adversarial_filed_findings TEXT NOT NULL DEFAULT '[]',
    security_outcome TEXT NOT NULL DEFAULT '',
    security_review_status TEXT NOT NULL DEFAULT '',
    security_review_error TEXT NOT NULL DEFAULT '',
    security_round_count INTEGER NOT NULL DEFAULT 0,
    security_findings TEXT NOT NULL DEFAULT '{}',
    security_filed_findings TEXT NOT NULL DEFAULT '[]',
    adversarial_epoch_count INTEGER NOT NULL DEFAULT 0,
    security_epoch_count INTEGER NOT NULL DEFAULT 0,
    adversarial_merge_policy TEXT NOT NULL DEFAULT '',
    adversarial_delivery TEXT NOT NULL DEFAULT '',
    adversarial_unresolved TEXT NOT NULL DEFAULT '{}',
    promotion_status TEXT NOT NULL DEFAULT '',
    promotion_url TEXT NOT NULL DEFAULT '',
    UNIQUE (repository, issue_number, attempt_number)
)""",
    """CREATE TABLE IF NOT EXISTS adversarial_rounds (
    round_id TEXT PRIMARY KEY,
    execution_id TEXT NOT NULL REFERENCES ai_executions(execution_id) ON DELETE CASCADE,
    stage TEXT NOT NULL DEFAULT 'uat',
    round_number INTEGER NOT NULL,
    fixer_provider TEXT NOT NULL DEFAULT '',
    fixer_model TEXT NOT NULL DEFAULT '',
    tester_provider TEXT NOT NULL DEFAULT '',
    tester_model TEXT NOT NULL DEFAULT '',
    tests_added INTEGER NOT NULL DEFAULT 0,
    tests_modified INTEGER NOT NULL DEFAULT 0,
    tests_failing_before INTEGER NOT NULL DEFAULT 0,
    tests_failing_after INTEGER NOT NULL DEFAULT 0,
    disputed INTEGER NOT NULL DEFAULT 0,
    dispute_resolution TEXT NOT NULL DEFAULT '',
    started_at TEXT NOT NULL DEFAULT '',
    completed_at TEXT NOT NULL DEFAULT '',
    duration_seconds DOUBLE PRECISION,
    findings_found INTEGER NOT NULL DEFAULT 0,
    findings_fixed INTEGER NOT NULL DEFAULT 0,
    findings_filed INTEGER NOT NULL DEFAULT 0,
    severity_counts TEXT NOT NULL DEFAULT '{}',
    epoch_number INTEGER NOT NULL DEFAULT 1,
    round_in_epoch INTEGER NOT NULL DEFAULT 0,
    fixer_effort TEXT NOT NULL DEFAULT '',
    tester_effort TEXT NOT NULL DEFAULT '',
    escalation_reason TEXT NOT NULL DEFAULT '',
    patch_fingerprint TEXT NOT NULL DEFAULT '',
    repeated_patch INTEGER NOT NULL DEFAULT 0,
    failure_fingerprint TEXT NOT NULL DEFAULT '',
    repeated_failure INTEGER NOT NULL DEFAULT 0,
    progress TEXT NOT NULL DEFAULT '',
    merge_policy TEXT NOT NULL DEFAULT '',
    failing_suites TEXT NOT NULL DEFAULT '[]',
    open_findings TEXT NOT NULL DEFAULT '[]',
    usage_json TEXT NOT NULL DEFAULT '{}',
    UNIQUE (execution_id, stage, round_number)
)""",
    """CREATE TABLE IF NOT EXISTS adversarial_epochs (
    epoch_id TEXT PRIMARY KEY,
    execution_id TEXT NOT NULL REFERENCES ai_executions(execution_id) ON DELETE CASCADE,
    stage TEXT NOT NULL,
    epoch_number INTEGER NOT NULL,
    first_round INTEGER NOT NULL DEFAULT 0,
    last_round INTEGER NOT NULL DEFAULT 0,
    merge_policy TEXT NOT NULL DEFAULT '',
    outcome TEXT NOT NULL DEFAULT '',
    progress INTEGER NOT NULL DEFAULT 0,
    stalled_epochs INTEGER NOT NULL DEFAULT 0,
    escalation_reason TEXT NOT NULL DEFAULT '',
    next_escalation TEXT NOT NULL DEFAULT '{}',
    fixers TEXT NOT NULL DEFAULT '[]',
    failing_suites TEXT NOT NULL DEFAULT '[]',
    findings TEXT NOT NULL DEFAULT '[]',
    disputes TEXT NOT NULL DEFAULT '[]',
    tests_added INTEGER NOT NULL DEFAULT 0,
    patch_fingerprints TEXT NOT NULL DEFAULT '[]',
    failure_fingerprint TEXT NOT NULL DEFAULT '',
    no_progress TEXT NOT NULL DEFAULT '{}',
    started_at TEXT NOT NULL DEFAULT '',
    completed_at TEXT NOT NULL DEFAULT '',
    duration_seconds DOUBLE PRECISION,
    usage_json TEXT NOT NULL DEFAULT '{}',
    UNIQUE (execution_id, stage, epoch_number)
)""",
    """CREATE TABLE IF NOT EXISTS ai_token_usage (
    id TEXT PRIMARY KEY,
    {usage_seq}
    execution_id TEXT NOT NULL DEFAULT '',
    repository TEXT NOT NULL DEFAULT '',
    issue_number INTEGER NOT NULL DEFAULT 0,
    workflow_run_id TEXT NOT NULL DEFAULT '',
    agent_run_id TEXT NOT NULL DEFAULT '',
    prompt_id TEXT NOT NULL DEFAULT '',
    provider TEXT NOT NULL DEFAULT '',
    model TEXT NOT NULL DEFAULT '',
    reasoning_effort TEXT NOT NULL DEFAULT '',
    agent_type TEXT NOT NULL DEFAULT '',
    prompt_type TEXT NOT NULL DEFAULT '',
    attempt_number INTEGER NOT NULL DEFAULT 1,
    input_tokens BIGINT,
    output_tokens BIGINT,
    reasoning_tokens BIGINT,
    cached_input_tokens BIGINT,
    total_tokens BIGINT,
    estimated_cost DOUBLE PRECISION,
    currency TEXT NOT NULL DEFAULT 'USD',
    started_at TEXT NOT NULL DEFAULT '',
    completed_at TEXT NOT NULL DEFAULT '',
    duration_ms BIGINT,
    success INTEGER NOT NULL DEFAULT 1,
    error_type TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT '',
    cache_read_tokens BIGINT,
    cache_write_tokens BIGINT,
    pricing_status TEXT NOT NULL DEFAULT '',
    pricing_version TEXT NOT NULL DEFAULT '',
    pricing_rate_id TEXT NOT NULL DEFAULT '',
    pricing_source TEXT NOT NULL DEFAULT '',
    input_rate_per_million DOUBLE PRECISION,
    cached_input_rate_per_million DOUBLE PRECISION,
    cache_write_rate_per_million DOUBLE PRECISION,
    output_rate_per_million DOUBLE PRECISION,
    session_reused INTEGER,
    session_role TEXT NOT NULL DEFAULT '',
    cache_input_tokens BIGINT,
    cache_savings_estimate DOUBLE PRECISION,
    reported_cost DOUBLE PRECISION
)""",
    """CREATE TABLE IF NOT EXISTS jev_decisions (
    decision_id TEXT PRIMARY KEY,
    execution_id TEXT NOT NULL DEFAULT '',
    issue_number INTEGER NOT NULL DEFAULT 0,
    repository TEXT NOT NULL DEFAULT '',
    decision_type TEXT NOT NULL DEFAULT '',
    input_fingerprint TEXT NOT NULL DEFAULT '',
    decision TEXT NOT NULL DEFAULT '',
    confidence DOUBLE PRECISION,
    scores TEXT NOT NULL DEFAULT '{}',
    reason_codes TEXT NOT NULL DEFAULT '[]',
    latency_ms DOUBLE PRECISION,
    provider TEXT NOT NULL DEFAULT 'jev',
    model TEXT NOT NULL DEFAULT '',
    version TEXT NOT NULL DEFAULT '',
    estimated_cost DOUBLE PRECISION,
    created_at TEXT NOT NULL DEFAULT '',
    fallback_used TEXT NOT NULL DEFAULT '',
    swarm_action TEXT NOT NULL DEFAULT '',
    recommendation_accepted INTEGER,
    workflow_outcome TEXT NOT NULL DEFAULT '',
    source TEXT NOT NULL DEFAULT '',
    error_type TEXT NOT NULL DEFAULT '',
    jev_enabled INTEGER NOT NULL DEFAULT 0,
    llm_calls_avoided INTEGER NOT NULL DEFAULT 0,
    estimated_tokens_avoided BIGINT,
    estimated_dollar_savings DOUBLE PRECISION
)""",
    """CREATE TABLE IF NOT EXISTS jev_score_comparisons (
    comparison_id TEXT PRIMARY KEY,
    execution_id TEXT NOT NULL DEFAULT '',
    repository TEXT NOT NULL DEFAULT '',
    issue_number INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT '',
    jev_status TEXT NOT NULL DEFAULT 'disabled',
    baseline_native_score DOUBLE PRECISION,
    baseline_normalized_score DOUBLE PRECISION,
    baseline_prompt_grade TEXT NOT NULL DEFAULT '',
    baseline_complexity INTEGER,
    baseline_task_type TEXT NOT NULL DEFAULT '',
    baseline_risk TEXT NOT NULL DEFAULT '',
    baseline_context TEXT NOT NULL DEFAULT '',
    baseline_provider TEXT NOT NULL DEFAULT '',
    baseline_model TEXT NOT NULL DEFAULT '',
    baseline_effort TEXT NOT NULL DEFAULT '',
    baseline_candidates TEXT NOT NULL DEFAULT '[]',
    baseline_inputs TEXT NOT NULL DEFAULT '{}',
    jev_native_score DOUBLE PRECISION,
    jev_normalized_score DOUBLE PRECISION,
    jev_component_scores TEXT NOT NULL DEFAULT '{}',
    jev_reason_codes TEXT NOT NULL DEFAULT '[]',
    jev_confidence DOUBLE PRECISION,
    jev_model TEXT NOT NULL DEFAULT '',
    jev_version TEXT NOT NULL DEFAULT '',
    modified_native_score DOUBLE PRECISION,
    modified_normalized_score DOUBLE PRECISION,
    modified_provider TEXT NOT NULL DEFAULT '',
    modified_model TEXT NOT NULL DEFAULT '',
    modified_effort TEXT NOT NULL DEFAULT '',
    modified_candidates TEXT NOT NULL DEFAULT '[]',
    score_delta_absolute DOUBLE PRECISION,
    score_delta_percent DOUBLE PRECISION,
    routing_changed INTEGER NOT NULL DEFAULT 0,
    estimated_jev_cost DOUBLE PRECISION,
    estimated_total_cost DOUBLE PRECISION,
    estimated_llm_calls_avoided INTEGER NOT NULL DEFAULT 0,
    estimated_tokens_avoided BIGINT,
    estimated_dollar_savings DOUBLE PRECISION,
    latency_ms DOUBLE PRECISION,
    workflow_outcome TEXT NOT NULL DEFAULT ''
)""",
    """CREATE INDEX IF NOT EXISTS adversarial_epochs_execution_idx ON adversarial_epochs(execution_id, stage, epoch_number)""",
    """CREATE INDEX IF NOT EXISTS adversarial_rounds_execution_idx ON adversarial_rounds(execution_id, stage, round_number)""",
    """CREATE INDEX IF NOT EXISTS ai_executions_issue_idx ON ai_executions(repository, issue_number, attempt_number)""",
    """CREATE INDEX IF NOT EXISTS ai_executions_upload_idx ON ai_executions(upload_status, updated_at)""",
    """CREATE INDEX IF NOT EXISTS ai_token_usage_agent_idx ON ai_token_usage(agent_type, provider, model)""",
    """CREATE INDEX IF NOT EXISTS ai_token_usage_execution_idx ON ai_token_usage(execution_id)""",
    """CREATE INDEX IF NOT EXISTS ai_token_usage_issue_idx ON ai_token_usage(repository, issue_number)""",
    """CREATE INDEX IF NOT EXISTS ai_token_usage_started_idx ON ai_token_usage(started_at)""",
    """CREATE INDEX IF NOT EXISTS jev_decisions_execution_idx ON jev_decisions(execution_id, created_at)""",
    """CREATE INDEX IF NOT EXISTS jev_decisions_issue_idx ON jev_decisions(repository, issue_number)""",
    """CREATE INDEX IF NOT EXISTS jev_decisions_type_idx ON jev_decisions(decision_type, source)""",
    """CREATE INDEX IF NOT EXISTS jev_score_comparisons_execution_idx ON jev_score_comparisons(execution_id)""",
    """CREATE INDEX IF NOT EXISTS jev_score_comparisons_status_idx ON jev_score_comparisons(jev_status, repository, created_at)""",
)

# The hosted migrations are one creation script, so every version up to the
# desktop SCHEMA_VERSION is recorded as applied the moment it runs.
CREATE_MIGRATIONS_TABLE = (
    "CREATE TABLE IF NOT EXISTS schema_migrations "
    "(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"
)
