-- Identity model of the hosted backend (issue #438, part of #413).
--
-- Gives sign-in a relational shape that more OIDC providers can join later:
-- a `users` row is a person, `user_identities` holds how they sign in (GitHub
-- is the only provider today: no username, email or password login), and
-- tenant ownership and membership are real foreign keys. Builds on 0001:
-- `web_users` / `web_sessions` become `users` / `sessions` (the rename keeps
-- their rows and every foreign key that points at them), and `github_id` and
-- `login` move out of `users` into `user_identities` after a backfill.
--
-- Idempotent and re-runnable: every statement is guarded (IF NOT EXISTS, or a
-- DO block that checks the catalog first), so applying it twice, or on a
-- database that already has the final shape, changes nothing. The per-tenant
-- worker schema (`t_<tenant>`, SCHEMA_VERSION) is not touched.

DO $$
DECLARE
    leftover BIGINT;
BEGIN
    IF to_regclass('web_users') IS NOT NULL AND to_regclass('users') IS NULL THEN
        ALTER TABLE web_users RENAME TO users;
    END IF;
    IF to_regclass('web_sessions') IS NOT NULL AND to_regclass('sessions') IS NULL THEN
        ALTER TABLE web_sessions RENAME TO sessions;
    END IF;
    -- Re-applying 0001 after this has run (psql -f over every file) recreates
    -- its two tables empty under the old names; drop those leftovers, but never
    -- one that holds rows.
    IF to_regclass('web_sessions') IS NOT NULL AND to_regclass('sessions') IS NOT NULL THEN
        EXECUTE 'SELECT count(*) FROM web_sessions' INTO leftover;
        IF leftover = 0 THEN
            DROP TABLE web_sessions;
        END IF;
    END IF;
    IF to_regclass('web_users') IS NOT NULL AND to_regclass('users') IS NOT NULL
       AND to_regclass('web_sessions') IS NULL THEN
        EXECUTE 'SELECT count(*) FROM web_users' INTO leftover;
        IF leftover = 0 THEN
            DROP TABLE web_users;
        END IF;
    END IF;
END
$$;

ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_platform_admin BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;

-- One row per way a person can sign in. `subject` is the provider's stable id
-- (the numeric GitHub id as text), `login` its human handle at last sign-in.
CREATE TABLE IF NOT EXISTS user_identities (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    provider    TEXT NOT NULL CHECK (provider <> ''),
    subject     TEXT NOT NULL CHECK (subject <> ''),
    login       TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (provider, subject)
);
CREATE INDEX IF NOT EXISTS user_identities_user_idx ON user_identities (user_id);

-- Move users.github_id / users.login into user_identities, once. The column
-- check keeps a re-run (where they are already gone) from touching them.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema = current_schema() AND table_name = 'users' AND column_name = 'github_id') THEN
        EXECUTE $sql$
            INSERT INTO user_identities (user_id, provider, subject, login, created_at)
            SELECT id, 'github', github_id::text, login, created_at FROM users
            ON CONFLICT (provider, subject) DO NOTHING
        $sql$;
        ALTER TABLE users DROP COLUMN github_id;
        ALTER TABLE users DROP COLUMN IF EXISTS login;
    END IF;
END
$$;

-- The tenant's owner. Nullable: tenants predate it and outlive a deleted user.
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS owner_user_id TEXT REFERENCES users (id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS tenants_owner_idx ON tenants (owner_user_id);

-- `tenant_memberships` (0001) already has both foreign keys, the role CHECK
-- and the (tenant, user) key; its user index is `tenant_memberships_user_idx`.
-- `sessions.user_id` (0001) already cascades from users and is indexed by
-- `web_sessions_user_idx`.

-- Platform-admin actions. The trail outlives the people in it, so both
-- references go NULL when a user is deleted rather than erasing the row.
CREATE TABLE IF NOT EXISTS admin_audit_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id   TEXT REFERENCES users (id) ON DELETE SET NULL,
    target_user_id  TEXT REFERENCES users (id) ON DELETE SET NULL,
    action          TEXT NOT NULL CHECK (action <> ''),
    detail          JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS admin_audit_log_actor_idx ON admin_audit_log (actor_user_id);
CREATE INDEX IF NOT EXISTS admin_audit_log_target_idx ON admin_audit_log (target_user_id);

INSERT INTO platform_migrations (version) VALUES ('0002_identity') ON CONFLICT DO NOTHING;
